import { DatePipe } from '@angular/common';
import { Component, computed, inject, OnInit, signal } from '@angular/core';
import { RouterLink } from '@angular/router';
import { SessionsService } from '../../services/sessions.service';
import { PageHeader } from '../../shared/components/page-header/page-header';
import { SkeletonGrid } from '../../shared/components/skeleton-grid/skeleton-grid';
import { StatePanel } from '../../shared/components/state-panel/state-panel';

@Component({selector:'app-sessions',standalone:true,imports:[RouterLink,DatePipe,PageHeader,SkeletonGrid,StatePanel],template:`
  <app-page-header eyebrow="Agenda" title="Sessions" description="Consultez les prochaines rencontres, choisissez votre rythme et gardez une vue claire sur votre agenda."><a class="my-link" routerLink="/my-sessions"><span class="material-symbols-rounded">bookmark</span>Mes sessions</a></app-page-header>
  <div class="session-toolbar"><div class="tabs" role="tablist"><button [class.active]="view()==='upcoming'" (click)="view.set('upcoming')">A venir</button><button [class.active]="view()==='past'" (click)="view.set('past')">Passees</button><button [class.active]="view()==='all'" (click)="view.set('all')">Toutes</button></div><label><span class="material-symbols-rounded">search</span><input type="search" placeholder="Rechercher" [value]="query()" (input)="query.set($any($event.target).value)"></label></div>
  @if(service.loading()){<app-skeleton-grid [count]="3"/>}@else if(service.error()){<app-state-panel icon="event_busy" title="Agenda indisponible" [message]="service.error()!" actionLabel="Reessayer" (action)="service.load(true)"/>}@else if(!filtered().length){<app-state-panel icon="calendar_today" title="Aucune session" message="Aucune session ne correspond a cette vue."/>}@else{<section class="session-grid">@for(session of filtered();track session.id){<article><div class="date"><time><b>{{session.startDate|date:'dd'}}</b><span>{{session.startDate|date:'MMM yyyy'}}</span></time><span [class.past]="isPast(session.endDate)">{{isPast(session.endDate)?'Terminee':'A venir'}}</span></div><div class="body"><small>Session de formation</small><h2>{{session.title}}</h2><p><span class="material-symbols-rounded">schedule</span>{{session.startDate|date:'HH:mm'}} - {{session.endDate|date:'HH:mm'}}</p><p><span class="material-symbols-rounded">videocam</span>En ligne</p></div><div class="foot"><button type="button" [class.joined]="service.isEnrolled(session.id)" (click)="toggle(session.id)"><span class="material-symbols-rounded">{{service.isEnrolled(session.id)?'check':'add'}}</span>{{service.isEnrolled(session.id)?'Ajoutee':'Ajouter'}}</button><a [routerLink]="['/sessions',session.id]" aria-label="Voir la session"><span class="material-symbols-rounded">arrow_forward</span></a></div></article>}</section>}
`,styles:[`
  .my-link{height:40px;padding:0 14px;display:flex;align-items:center;gap:7px;border-radius:6px;background:var(--ink);color:var(--surface);font-size:.74rem;font-weight:700}.my-link span{font-size:17px}.session-toolbar{display:flex;align-items:center;justify-content:space-between;gap:16px;margin-bottom:22px}.tabs{display:flex;padding:3px;border:1px solid var(--border);border-radius:7px;background:var(--surface)}.tabs button{height:34px;padding:0 14px;border:0;border-radius:5px;background:transparent;color:var(--muted);font-size:.72rem;cursor:pointer}.tabs button.active{background:var(--surface-2);color:var(--ink);font-weight:700}.session-toolbar label{width:260px;height:40px;padding:0 10px;display:flex;align-items:center;gap:7px;border:1px solid var(--border);border-radius:6px;background:var(--surface)}.session-toolbar label span{font-size:18px;color:var(--muted)}.session-toolbar input{min-width:0;flex:1;border:0;outline:0;background:transparent;color:var(--ink)}.session-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:15px}.session-grid article{border:1px solid var(--border);border-radius:8px;background:var(--surface);overflow:hidden;transition:transform 160ms ease,box-shadow 160ms ease}.session-grid article:hover{transform:translateY(-2px);box-shadow:var(--shadow)}.date{padding:18px 20px;display:flex;align-items:center;justify-content:space-between;background:var(--surface-2);border-bottom:1px solid var(--border)}time{display:flex;align-items:baseline;gap:7px}time b{font-size:1.65rem}time span{color:var(--muted);font-size:.68rem;text-transform:uppercase}.date>span{padding:4px 7px;border-radius:4px;background:color-mix(in srgb,var(--teal) 12%,transparent);color:var(--teal);font-size:.62rem;font-weight:700}.date>span.past{background:var(--border);color:var(--muted)}.body{padding:21px}.body>small{color:var(--brand);font-size:.63rem;font-weight:700;text-transform:uppercase}.body h2{min-height:48px;margin:9px 0 17px;font-size:1rem;line-height:1.45}.body p{margin:7px 0;display:flex;align-items:center;gap:7px;color:var(--muted);font-size:.72rem}.body p span{font-size:17px}.foot{padding:14px 18px;display:flex;justify-content:space-between;border-top:1px solid var(--border)}.foot button{height:34px;padding:0 10px;display:flex;align-items:center;gap:5px;border:1px solid var(--border);border-radius:5px;background:var(--surface);color:var(--ink);font-size:.68rem;font-weight:600;cursor:pointer}.foot button.joined{color:var(--teal);border-color:color-mix(in srgb,var(--teal) 35%,var(--border))}.foot button span,.foot a span{font-size:17px}.foot a{width:34px;height:34px;display:grid;place-items:center;border-radius:5px;background:var(--ink);color:var(--surface)}@media(max-width:1000px){.session-grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:650px){.session-toolbar{align-items:stretch;flex-direction:column}.session-toolbar label{width:100%}.tabs{width:100%}.tabs button{flex:1}.session-grid{grid-template-columns:1fr}}
`]})
export class Sessions implements OnInit{readonly service=inject(SessionsService);readonly view=signal<'upcoming'|'past'|'all'>('upcoming');readonly query=signal('');readonly filtered=computed(()=>{const now=Date.now(),q=this.query().toLowerCase();return this.service.sessions().filter(s=>(this.view()==='all'||(this.view()==='past'?new Date(s.endDate).getTime()<now:new Date(s.endDate).getTime()>=now))&&(!q||s.title.toLowerCase().includes(q))).sort((a,b)=>a.startDate.localeCompare(b.startDate));});ngOnInit():void{this.service.load();}isPast(date:string):boolean{return new Date(date).getTime()<Date.now();}toggle(id:string):void{this.service.isEnrolled(id)?this.service.leave(id):this.service.join(id);}}
