import { DatePipe } from '@angular/common';
import { Component, inject, signal } from '@angular/core';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { ActivatedRoute, RouterLink } from '@angular/router';
import { TrainingSession } from '../../models/session.model';
import { FormationsService } from '../../services/formations.service';
import { SessionsService } from '../../services/sessions.service';
import { StatePanel } from '../../shared/components/state-panel/state-panel';

@Component({selector:'app-session-details',standalone:true,imports:[RouterLink,DatePipe,StatePanel],template:`
  @if(loading()){<div class="loading"></div>}@else if(!session()){<app-state-panel icon="event_busy" title="Session introuvable" message="Cette session n'est plus accessible."/>}@else{<a routerLink="/sessions" class="back"><span class="material-symbols-rounded">arrow_back</span>Retour aux sessions</a><div class="detail-layout"><main><section class="session-hero"><div class="status"><span></span>{{past()?'Session terminee':'Session a venir'}}</div><h1>{{session()!.title}}</h1><p>{{formationTitle()}}</p><div class="schedule"><time><span>{{session()!.startDate|date:'EEEE'}}</span><b>{{session()!.startDate|date:'dd'}}</b><small>{{session()!.startDate|date:'MMMM yyyy'}}</small></time><div><span><i class="material-symbols-rounded">schedule</i><b>{{session()!.startDate|date:'HH:mm'}} - {{session()!.endDate|date:'HH:mm'}}</b></span><span><i class="material-symbols-rounded">videocam</i><b>Session en ligne</b></span></div></div></section><section class="info"><p class="eyebrow">Preparation</p><h2>Avant la session</h2><div class="steps"><div><span>1</span><p><b>Verifiez votre connexion</b><small>Utilisez une connexion stable et un navigateur recent.</small></p></div><div><span>2</span><p><b>Preparez votre espace</b><small>Installez-vous au calme avec un casque si possible.</small></p></div><div><span>3</span><p><b>Testez vos connaissances</b><small>Le coach IA peut vous aider a revoir les notions essentielles.</small></p></div></div></section></main><aside><div class="action panel"><span class="material-symbols-rounded">event_available</span><h2>{{service.isEnrolled(session()!.id)?'Session ajoutee':'Ajouter a mon agenda'}}</h2><p>Retrouvez cette session dans votre espace personnel.</p><button (click)="toggle()" [class.secondary]="service.isEnrolled(session()!.id)">{{service.isEnrolled(session()!.id)?'Retirer de mes sessions':'Ajouter la session'}}</button>@if(session()!.meetingLink&&!past()){<a [href]="session()!.meetingLink" target="_blank" rel="noopener">Rejoindre la reunion <span class="material-symbols-rounded">open_in_new</span></a>}<a class="coach" [routerLink]="['/anam',session()!.id]"><span class="material-symbols-rounded">neurology</span>Preparer avec le coach IA</a></div></aside></div>}
`,styles:[`
  .back{display:inline-flex;align-items:center;gap:6px;margin-bottom:22px;color:var(--muted);font-size:.75rem}.back span{font-size:17px}.detail-layout{display:grid;grid-template-columns:minmax(0,1fr) 320px;gap:24px}.session-hero{padding:42px;border-radius:8px;background:#292c35;color:white}.status{display:flex;align-items:center;gap:7px;color:#7adbc0;font-size:.68rem;font-weight:700;text-transform:uppercase}.status span{width:7px;height:7px;border-radius:50%;background:currentColor}.session-hero h1{max-width:720px;margin:22px 0 10px;font-size:clamp(2rem,4vw,3.2rem);line-height:1.1}.session-hero>p{margin:0;color:rgba(255,255,255,.6)}.schedule{margin-top:42px;padding-top:28px;display:flex;align-items:center;gap:30px;border-top:1px solid rgba(255,255,255,.13)}time{width:100px;height:112px;display:grid;place-items:center;align-content:center;border-radius:7px;background:white;color:#242630}time span,time small{font-size:.62rem;text-transform:uppercase;color:#686d79}time b{margin:5px 0;font-size:2rem}.schedule>div{display:grid;gap:16px}.schedule>div span{display:flex;align-items:center;gap:9px}.schedule i{color:#8e90f4}.schedule b{font-size:.76rem}.info{padding:38px 8px}.info .eyebrow{margin:0 0 7px}.info h2{margin:0 0 20px}.steps{display:grid;gap:10px}.steps>div{padding:16px;display:flex;gap:14px;border:1px solid var(--border);border-radius:7px;background:var(--surface)}.steps>div>span{width:28px;height:28px;flex:0 0 auto;display:grid;place-items:center;border-radius:50%;background:var(--surface-2);color:var(--brand);font-size:.7rem;font-weight:700}.steps p{margin:0;display:grid;gap:5px}.steps b{font-size:.78rem}.steps small{color:var(--muted);line-height:1.5}.action{position:sticky;top:104px;padding:25px}.action>span{width:44px;height:44px;display:grid;place-items:center;border-radius:7px;background:color-mix(in srgb,var(--teal) 12%,transparent);color:var(--teal)}.action h2{margin:22px 0 8px;font-size:1.05rem}.action p{margin:0 0 18px;color:var(--muted);font-size:.75rem;line-height:1.6}.action button,.action>a:not(.coach){width:100%;min-height:42px;margin-top:9px;border:0;border-radius:6px;display:flex;align-items:center;justify-content:center;gap:7px;background:var(--brand);color:white;font-size:.72rem;font-weight:700;cursor:pointer}.action button.secondary{background:var(--surface-2);color:var(--muted)}.action a span{font-size:16px}.action .coach{margin-top:18px;padding-top:18px;display:flex;align-items:center;gap:8px;border-top:1px solid var(--border);color:var(--brand-strong);font-size:.73rem;font-weight:600}.loading{height:520px;border-radius:8px;background:var(--surface-2);animation:pulse 1s infinite}@keyframes pulse{50%{opacity:.55}}@media(max-width:900px){.detail-layout{grid-template-columns:1fr}.detail-layout aside{grid-row:1}.action{position:static}}@media(max-width:600px){.session-hero{padding:28px 20px}.schedule{align-items:flex-start;flex-direction:column}}
`]})
export class SessionDetails{readonly service=inject(SessionsService);private readonly formations=inject(FormationsService);private readonly route=inject(ActivatedRoute);readonly session=signal<TrainingSession|null>(null);readonly loading=signal(true);constructor(){this.formations.load();this.service.getById(this.route.snapshot.paramMap.get('id')!).pipe(takeUntilDestroyed()).subscribe({next:value=>{this.session.set(value);this.loading.set(false);},error:()=>this.loading.set(false)});}formationTitle():string{return this.formations.formations().find(f=>f.id===this.session()?.formationId)?.title??'Formation';}past():boolean{return new Date(this.session()!.endDate).getTime()<Date.now();}toggle():void{const id=this.session()!.id;this.service.isEnrolled(id)?this.service.leave(id):this.service.join(id);}}
