import { Component, computed, inject, OnInit, signal } from '@angular/core';
import { RouterLink } from '@angular/router';
import { CategoriesService } from '../../services/categories.service';
import { FormationsService } from '../../services/formations.service';
import { PageHeader } from '../../shared/components/page-header/page-header';
import { SkeletonGrid } from '../../shared/components/skeleton-grid/skeleton-grid';
import { StatePanel } from '../../shared/components/state-panel/state-panel';

@Component({selector:'app-categories',standalone:true,imports:[RouterLink,PageHeader,SkeletonGrid,StatePanel],template:`
  <app-page-header eyebrow="Catalogue" title="Categories" description="Explorez les domaines disponibles et trouvez le parcours qui correspond a votre prochain objectif." />
  <div class="toolbar"><label><span class="material-symbols-rounded">search</span><input type="search" placeholder="Rechercher une categorie" [value]="query()" (input)="query.set($any($event.target).value)" aria-label="Rechercher une categorie"></label><span>{{ filtered().length }} domaines</span></div>
  @if(categories.loading()){<app-skeleton-grid/>}
  @else if(categories.error()){<app-state-panel icon="cloud_off" title="Catalogue indisponible" [message]="categories.error()!" actionLabel="Reessayer" (action)="categories.load(true)"/>}
  @else if(!filtered().length){<app-state-panel icon="search_off" title="Aucun resultat" message="Essayez avec un autre mot-cle."/>}
  @else{<section class="category-grid">@for(category of filtered();track category.id;let index=$index){<a class="category-card" [routerLink]="['/formations']" [queryParams]="{category:category.id}"><div class="card-top"><span class="category-icon material-symbols-rounded">{{icons[index%icons.length]}}</span><small>{{formationCount(category.id)}} formation{{formationCount(category.id)>1?'s':''}}</small></div><h2>{{category.name}}</h2><p>{{category.description}}</p><div class="card-foot"><span>Explorer le domaine</span><span class="material-symbols-rounded">arrow_forward</span></div></a>}</section>}
`,styles:[`
  .toolbar{display:flex;align-items:center;justify-content:space-between;gap:20px;margin-bottom:22px}.toolbar label{width:min(420px,100%);height:42px;padding:0 12px;display:flex;align-items:center;gap:9px;border:1px solid var(--border);border-radius:6px;background:var(--surface)}.toolbar label span{color:var(--muted);font-size:19px}.toolbar input{min-width:0;flex:1;border:0;outline:0;background:transparent;color:var(--ink)}.toolbar>span{color:var(--muted);font-size:.75rem}.category-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:15px}.category-card{min-height:230px;padding:22px;display:flex;flex-direction:column;border:1px solid var(--border);border-radius:8px;background:var(--surface);transition:transform 170ms ease,border-color 170ms ease,box-shadow 170ms ease}.category-card:hover{transform:translateY(-3px);border-color:color-mix(in srgb,var(--brand) 40%,var(--border));box-shadow:var(--shadow)}.card-top{display:flex;align-items:center;justify-content:space-between}.category-icon{width:42px;height:42px;border-radius:7px;display:grid;place-items:center;background:color-mix(in srgb,var(--brand) 11%,transparent);color:var(--brand);font-size:22px}.card-top small{color:var(--muted);font-size:.68rem}.category-card h2{margin:28px 0 9px;font-size:1.05rem}.category-card p{margin:0;color:var(--muted);font-size:.78rem;line-height:1.6}.card-foot{margin-top:auto;padding-top:19px;display:flex;align-items:center;justify-content:space-between;color:var(--brand-strong);font-size:.73rem;font-weight:600}.card-foot .material-symbols-rounded{font-size:18px;transition:transform 160ms}.category-card:hover .card-foot .material-symbols-rounded{transform:translateX(3px)}@media(max-width:950px){.category-grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:600px){.toolbar>span{display:none}.category-grid{grid-template-columns:1fr}}
`]})
export class Categories implements OnInit{readonly categories=inject(CategoriesService);private readonly formations=inject(FormationsService);readonly query=signal('');readonly icons=['code','brush','monitoring','campaign','language','science','account_balance'];readonly filtered=computed(()=>{const q=this.query().trim().toLowerCase();return this.categories.categories().filter(c=>!q||`${c.name} ${c.description}`.toLowerCase().includes(q));});ngOnInit():void{this.categories.load();this.formations.load();}formationCount(id:string):number{return this.formations.formations().filter(f=>f.categoryId===id).length;}}
