import { DatePipe } from '@angular/common';
import { Component, inject, OnInit } from '@angular/core';
import { RouterLink } from '@angular/router';
import { SessionsService } from '../../services/sessions.service';
import { PageHeader } from '../../shared/components/page-header/page-header';
import { SkeletonGrid } from '../../shared/components/skeleton-grid/skeleton-grid';
import { StatePanel } from '../../shared/components/state-panel/state-panel';

@Component({selector:'app-my-sessions',standalone:true,imports:[RouterLink,DatePipe,PageHeader,SkeletonGrid,StatePanel],template:`
  <app-page-header eyebrow="Mon espace" title="Mes sessions" description="Toutes les sessions ajoutees a votre agenda, reunies au meme endroit."><a class="browse" routerLink="/sessions"><span class="material-symbols-rounded">add</span>Explorer les sessions</a></app-page-header>
  @if(service.loading()){<app-skeleton-grid [count]="3"/>}@else if(!service.mySessions().length){<app-state-panel icon="bookmark_add" title="Votre agenda est encore vide" message="Explorez les sessions disponibles et ajoutez celles qui vous interessent." actionLabel="Voir les sessions" (action)="goToSessions()"/>}@else{<div class="timeline">@for(session of service.mySessions();track session.id){<article><time><b>{{session.startDate|date:'dd'}}</b><span>{{session.startDate|date:'MMM'}}</span></time><div><small>{{session.startDate|date:'EEEE d MMMM yyyy'}}</small><h2>{{session.title}}</h2><p><span class="material-symbols-rounded">schedule</span>{{session.startDate|date:'HH:mm'}} - {{session.endDate|date:'HH:mm'}} <span class="dot"></span><span class="material-symbols-rounded">videocam</span>En ligne</p></div><div class="actions"><a [routerLink]="['/sessions',session.id]">Voir le detail</a><button type="button" (click)="service.leave(session.id)" aria-label="Retirer la session"><span class="material-symbols-rounded">delete</span></button></div></article>}</div>}
`,styles:[`
  .browse{height:40px;padding:0 13px;display:flex;align-items:center;gap:6px;border-radius:6px;background:var(--ink);color:var(--surface);font-size:.72rem;font-weight:700}.browse span{font-size:17px}.timeline{position:relative;display:grid;gap:12px}.timeline:before{content:'';position:absolute;left:33px;top:0;bottom:0;width:1px;background:var(--border)}article{position:relative;min-height:112px;padding:18px 18px 18px 96px;display:flex;align-items:center;gap:20px;border:1px solid var(--border);border-radius:8px;background:var(--surface);transition:transform 160ms ease,box-shadow 160ms ease}article:hover{transform:translateX(3px);box-shadow:var(--shadow)}time{position:absolute;left:12px;width:44px;height:54px;z-index:1;display:grid;place-items:center;align-content:center;border-radius:6px;background:var(--ink);color:var(--surface);line-height:1}time b{font-size:1.1rem}time span{margin-top:5px;font-size:.58rem;text-transform:uppercase}article>div:nth-child(2){flex:1;min-width:0}article small{color:var(--brand);font-size:.65rem;font-weight:700;text-transform:capitalize}article h2{margin:7px 0;font-size:.95rem}article p{margin:0;display:flex;align-items:center;gap:5px;color:var(--muted);font-size:.68rem}article p .material-symbols-rounded{font-size:15px}.dot{width:3px;height:3px;margin:0 6px;border-radius:50%;background:var(--muted)}.actions{display:flex;align-items:center;gap:8px}.actions a{height:36px;padding:0 12px;display:grid;place-items:center;border-radius:5px;background:var(--brand);color:white;font-size:.68rem;font-weight:700}.actions button{width:36px;height:36px;border:1px solid var(--border);border-radius:5px;display:grid;place-items:center;background:var(--surface);color:var(--muted);cursor:pointer}.actions button span{font-size:18px}@media(max-width:650px){.timeline:before{display:none}article{padding:18px;align-items:flex-start;flex-wrap:wrap}time{position:static;flex:0 0 44px}.actions{width:100%;justify-content:flex-end}article>div:nth-child(2){width:calc(100% - 64px);flex:none}article p{flex-wrap:wrap}}
`]})
export class MySessions implements OnInit{readonly service=inject(SessionsService);ngOnInit():void{this.service.load();}goToSessions():void{location.href='/sessions';}}
