import { Component, inject } from '@angular/core';
import { Router } from '@angular/router';
import { AuthService } from '../../core/services/auth.service';
import { ThemeService } from '../../core/services/theme.service';
import { PageHeader } from '../../shared/components/page-header/page-header';

@Component({selector:'app-profile',standalone:true,imports:[PageHeader],template:`
  <app-page-header eyebrow="Mon espace" title="Profil" description="Gerez vos informations personnelles et vos preferences d'apprentissage." />
  <div class="profile-grid"><main><section class="identity panel"><div class="avatar">{{auth.currentUser()?.initials}}</div><div><h2>{{auth.currentUser()?.name}}</h2><p>{{auth.currentUser()?.email}}</p><span>Apprenant</span></div><button type="button"><span class="material-symbols-rounded">edit</span>Modifier</button></section><section class="panel settings"><header><h2>Informations personnelles</h2><p>Les informations associees a votre compte.</p></header><div class="field-grid"><label>Nom complet<input [value]="auth.currentUser()?.name" readonly></label><label>Adresse e-mail<input [value]="auth.currentUser()?.email" readonly></label><label>Identifiant<input [value]="auth.currentUser()?.id" readonly></label><label>Langue<select><option>Francais</option><option>English</option></select></label></div></section><section class="panel settings"><header><h2>Preferences</h2><p>Personnalisez votre experience sur la plateforme.</p></header><button class="preference" type="button" (click)="theme.toggle()"><span class="material-symbols-rounded">{{theme.mode()==='light'?'dark_mode':'light_mode'}}</span><span><b>Apparence</b><small>Theme {{theme.mode()==='light'?'clair':'sombre'}}</small></span><i class="material-symbols-rounded">chevron_right</i></button></section></main><aside><div class="panel account"><h2>Compte</h2><button type="button"><span class="material-symbols-rounded">lock</span>Changer le mot de passe</button><button class="logout" type="button" (click)="logout()"><span class="material-symbols-rounded">logout</span>Se deconnecter</button></div><div class="panel help"><span class="material-symbols-rounded">support_agent</span><h2>Besoin d'aide ?</h2><p>Notre equipe vous accompagne pour toute question sur votre espace.</p><a href="mailto:support@forma.ma">Contacter le support</a></div></aside></div>
`,styles:[`
  .profile-grid{display:grid;grid-template-columns:minmax(0,1fr) 300px;gap:20px}.profile-grid main{display:grid;gap:16px}.identity{padding:24px;display:flex;align-items:center;gap:16px}.avatar{width:68px;height:68px;display:grid;place-items:center;border-radius:50%;background:var(--ink);color:var(--surface);font-size:1.25rem;font-weight:700}.identity>div:nth-child(2){flex:1}.identity h2{margin:0 0 5px;font-size:1.05rem}.identity p{margin:0;color:var(--muted);font-size:.75rem}.identity div span{display:inline-block;margin-top:9px;padding:4px 7px;border-radius:4px;background:color-mix(in srgb,var(--brand) 10%,transparent);color:var(--brand);font-size:.62rem;font-weight:700}.identity button{height:36px;padding:0 11px;display:flex;align-items:center;gap:6px;border:1px solid var(--border);border-radius:5px;background:var(--surface);color:var(--ink);font-size:.68rem}.identity button span{font-size:16px}.settings{padding:24px}.settings header{margin-bottom:22px}.settings h2,.account h2,.help h2{margin:0;font-size:.95rem}.settings header p{margin:6px 0 0;color:var(--muted);font-size:.7rem}.field-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:16px}.field-grid label{display:grid;gap:6px;color:var(--muted);font-size:.65rem;font-weight:600}.field-grid input,.field-grid select{width:100%;height:40px;padding:0 10px;border:1px solid var(--border);border-radius:5px;background:var(--surface-2);color:var(--ink);font-size:.72rem}.preference{width:100%;padding:14px;border:1px solid var(--border);border-radius:6px;display:flex;align-items:center;gap:12px;background:var(--surface);color:var(--ink);cursor:pointer}.preference>span:first-child{width:38px;height:38px;display:grid;place-items:center;border-radius:6px;background:var(--surface-2);color:var(--brand)}.preference>span:nth-child(2){display:grid;gap:4px;text-align:left;flex:1}.preference b{font-size:.75rem}.preference small{color:var(--muted);font-size:.65rem}.preference i{color:var(--muted);font-style:normal}.profile-grid aside{display:grid;align-content:start;gap:16px}.account{padding:21px}.account h2{margin-bottom:15px}.account button{width:100%;height:42px;padding:0 8px;display:flex;align-items:center;gap:8px;border:0;border-top:1px solid var(--border);background:transparent;color:var(--ink);font-size:.7rem;cursor:pointer}.account button span{font-size:18px}.account button.logout{color:var(--danger)}.help{padding:22px}.help>span{width:42px;height:42px;display:grid;place-items:center;border-radius:7px;background:color-mix(in srgb,var(--teal) 12%,transparent);color:var(--teal)}.help h2{margin-top:18px}.help p{color:var(--muted);font-size:.7rem;line-height:1.6}.help a{display:inline-block;margin-top:6px;color:var(--brand-strong);font-size:.7rem;font-weight:700}@media(max-width:900px){.profile-grid{grid-template-columns:1fr}}@media(max-width:600px){.identity{align-items:flex-start;flex-wrap:wrap}.identity button{margin-left:84px}.field-grid{grid-template-columns:1fr}}
`]})
export class Profile{readonly auth=inject(AuthService);readonly theme=inject(ThemeService);private readonly router=inject(Router);logout():void{this.auth.logout();void this.router.navigate(['/login']);}}
