import { Component, computed, inject, OnInit, signal } from '@angular/core';
import { ActivatedRoute, RouterLink } from '@angular/router';
import { CategoriesService } from '../../services/categories.service';
import { FormationsService } from '../../services/formations.service';
import { PageHeader } from '../../shared/components/page-header/page-header';
import { SkeletonGrid } from '../../shared/components/skeleton-grid/skeleton-grid';
import { StatePanel } from '../../shared/components/state-panel/state-panel';

@Component({selector:'app-formations',standalone:true,imports:[RouterLink,PageHeader,SkeletonGrid,StatePanel],template:`
  <app-page-header eyebrow="Catalogue" title="Formations" description="Des parcours concrets, organises pour transformer chaque heure d'apprentissage en progression visible." />
  <div class="filters">
    <label class="search"><span class="material-symbols-rounded">search</span><input type="search" placeholder="Rechercher une formation" [value]="query()" (input)="query.set($any($event.target).value)"></label>
    <label class="select"><span>Categorie</span><select [value]="categoryId()" (change)="categoryId.set($any($event.target).value)"><option value="">Toutes</option>@for(category of categories.categories();track category.id){<option [value]="category.id">{{category.name}}</option>}</select></label>
    <label class="select"><span>Niveau</span><select [value]="level()" (change)="level.set($any($event.target).value)"><option value="">Tous</option>@for(item of levels();track item){<option [value]="item">{{item}}</option>}</select></label>
    @if(query()||categoryId()||level()){<button type="button" (click)="reset()"><span class="material-symbols-rounded">close</span>Effacer</button>}
  </div>
  <div class="result-meta"><span>{{filtered().length}} formation{{filtered().length>1?'s':''}}</span><span>Triees par pertinence</span></div>
  @if(formations.loading()){<app-skeleton-grid/>}
  @else if(formations.error()){<app-state-panel icon="cloud_off" title="Catalogue indisponible" [message]="formations.error()!" actionLabel="Reessayer" (action)="formations.load(true)"/>}
  @else if(!filtered().length){<app-state-panel icon="filter_alt_off" title="Aucune formation trouvee" message="Modifiez vos criteres pour elargir la recherche." actionLabel="Reinitialiser" (action)="reset()"/>}
  @else{<section class="course-grid">@for(formation of filtered();track formation.id;let index=$index){<article class="course-card"><a [routerLink]="['/formations',formation.id]" class="visual" [class]="'visual tone-'+index%4"><span class="material-symbols-rounded">{{courseIcons[index%courseIcons.length]}}</span><i>{{formation.level}}</i></a><div class="course-body"><small>{{categoryName(formation.categoryId)}}</small><a [routerLink]="['/formations',formation.id]"><h2>{{formation.title}}</h2></a><p>{{formation.description}}</p><div class="course-meta"><span><i class="material-symbols-rounded">schedule</i>{{formation.duration}} h</span><span><i class="material-symbols-rounded">signal_cellular_alt</i>{{formation.level}}</span></div></div></article>}</section>}
`,styles:[`
  .filters{display:flex;align-items:end;gap:10px;margin-bottom:18px}.search{width:min(370px,100%);height:44px;padding:0 12px;display:flex;align-items:center;gap:8px;border:1px solid var(--border);border-radius:6px;background:var(--surface)}.search span{font-size:19px;color:var(--muted)}.search input{min-width:0;flex:1;border:0;outline:0;color:var(--ink);background:transparent}.select{display:grid;gap:5px}.select>span{color:var(--muted);font-size:.65rem;font-weight:600}.select select{height:44px;min-width:150px;padding:0 32px 0 11px;border:1px solid var(--border);border-radius:6px;color:var(--ink);background:var(--surface)}.filters button{height:44px;padding:0 11px;display:flex;align-items:center;gap:4px;border:0;background:transparent;color:var(--muted);font-size:.72rem;cursor:pointer}.filters button span{font-size:16px}.result-meta{display:flex;justify-content:space-between;margin-bottom:14px;color:var(--muted);font-size:.7rem}.course-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:16px}.course-card{overflow:hidden;border:1px solid var(--border);border-radius:8px;background:var(--surface);transition:transform 170ms ease,box-shadow 170ms ease}.course-card:hover{transform:translateY(-3px);box-shadow:var(--shadow)}.visual{height:160px;position:relative;display:grid;place-items:center;background:#e9ecf8}.visual>span{font-size:54px;color:#5759ba}.visual>i{position:absolute;left:14px;bottom:14px;padding:5px 8px;border-radius:4px;background:rgba(255,255,255,.88);color:#292b35;font-size:.63rem;font-style:normal;font-weight:700}.visual.tone-1{background:#e1f2ee}.visual.tone-1>span{color:#177f73}.visual.tone-2{background:#f3e9dc}.visual.tone-2>span{color:#af6b24}.visual.tone-3{background:#efe5ea}.visual.tone-3>span{color:#9b4f6c}.course-body{padding:19px}.course-body>small{color:var(--brand);font-size:.65rem;font-weight:700;text-transform:uppercase}.course-body h2{min-height:46px;margin:9px 0 8px;font-size:1rem;line-height:1.45}.course-body p{height:42px;margin:0;overflow:hidden;color:var(--muted);font-size:.75rem;line-height:1.45}.course-meta{margin-top:18px;padding-top:14px;display:flex;gap:18px;border-top:1px solid var(--border);color:var(--muted);font-size:.68rem}.course-meta span{display:flex;align-items:center;gap:5px}.course-meta i{font-size:15px;font-style:normal}@media(max-width:1000px){.course-grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:720px){.filters{align-items:stretch;flex-wrap:wrap}.search{width:100%}.select{flex:1}.select select{width:100%;min-width:0}.course-grid{grid-template-columns:1fr}} 
`]})
export class Formations implements OnInit{readonly formations=inject(FormationsService);readonly categories=inject(CategoriesService);private readonly route=inject(ActivatedRoute);readonly query=signal('');readonly categoryId=signal(this.route.snapshot.queryParamMap.get('category')??'');readonly level=signal('');readonly courseIcons=['devices','psychology','query_stats','campaign','code','design_services'];readonly levels=computed(()=>[...new Set(this.formations.formations().map(f=>f.level))]);readonly filtered=computed(()=>{const q=this.query().trim().toLowerCase();return this.formations.formations().filter(f=>(!q||`${f.title} ${f.description}`.toLowerCase().includes(q))&&(!this.categoryId()||f.categoryId===this.categoryId())&&(!this.level()||f.level===this.level()));});ngOnInit():void{this.formations.load();this.categories.load();}categoryName(id:string):string{return this.categories.categories().find(c=>c.id===id)?.name??'Formation';}reset():void{this.query.set('');this.categoryId.set('');this.level.set('');}}
